Repository ucsb-cs156-w24/proj-courses-w24-5pm-4, pull requests merged in 2024-03, with the labels that each got.

#26 FEATURE: Add link to developer/GH info in Admin dropdown
  frontend/src/main/components/Nav/AppNavbar.js
  src/main/resources/application.properties
Labels: 5 points

#33 BUG: Deleting a personal schedule doesn't delete associated PSCourses
  src/main/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesController.java
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesControllerTests.java
Labels: 20 points

#31 BUG: Can't immediately search for graduate courses
  frontend/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
  frontend/src/tests/components/BasicCourseSearch/BasicCourseSearchForm.test.js
  frontend/src/tests/components/Levels/SingleLevelDropdown.test.js
Labels: 10 points

#32 FEATURE: Add frontend for job to update all courses in a range of quarters
  frontend/src/main/components/Jobs/UpdateCoursesByQuarterRangeJobForm.js
  frontend/src/main/pages/AdminJobsPage.js
  frontend/src/stories/components/Jobs/UpdateCoursesByQuarterRangeJobForm.stories.js
  frontend/src/tests/components/Jobs/UpdateCoursesByQuarterRangeJobForm.test.js
  frontend/src/tests/pages/AdminJobsPage.test.js
Labels: 10 points

#18 FEATURE: Add edit page for personal schedules
  frontend/src/main/components/PersonalSchedules/PersonalScheduleForm.js
  frontend/src/main/components/Quarters/SingleQuarterDropdown.js
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesEditPage.js
  frontend/src/stories/pages/HomePage/PersonalSchedules/PersonalSchedulesEditPage.stories.js
  frontend/src/tests/components/PersonalSchedules/PersonalScheduleForm.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesEditPage.test.js
Labels: 20 points

#34 REFACTOR: Simplify "Personal schedule" navigation
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/Courses/PSCourseIndexPage.js
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesIndexPage.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesIndexPage.test.js
  src/main/resources/application.properties
Labels: 10 points

#28 FEATURE: More descriptive personal courses page
  frontend/src/fixtures/pscourseFixtures.js
  frontend/src/main/components/Courses/CourseForm.js
  frontend/src/main/components/Courses/CourseTable.js
  frontend/src/main/pages/Courses/PSCourseIndexPage.js
  frontend/src/tests/components/Courses/CourseForm.test.js
  frontend/src/tests/components/Courses/CourseTable.test.js
  frontend/src/tests/pages/Courses/CoursesIndexPage.test.js
  src/main/java/edu/ucsb/cs156/courses/controllers/PSCourseController.java
  src/main/java/edu/ucsb/cs156/courses/entities/PSCourse.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PSCourseControllerTests.java
Labels: 10 points, FIXME - Peer CR
